
export const COLORS = {
  pink: '#FFB3D9',
  blue: '#A8D8FF',
  green: '#B5E7C2',
  yellow: '#FFF4A3',
  purple: '#D4B5F1',
  white: '#FFF9F0',
  text: '#4A4A4A'
};

export const GAME_CONFIG = {
  // Timers (seconds)
  DURATION_TRAIN: 10,
  DURATION_SLEEP: 15, // Nap duration
  DURATION_LONG_SLEEP: 21600, // 6 hours in seconds
  DURATION_CLEAN: 3, // Generic
  DURATION_BRUSH: 5,
  DURATION_WASH_FACE: 4,
  DURATION_SHOWER: 7,
  DURATION_FEED: 2,
  DURATION_DRINK: 2,
  DURATION_SOCIAL: 10,
  DURATION_PARTY: 15, // New
  
  // Work Session Configuration
  WORK_SESSION_DURATION: 360, 
  POMODORO_INTERVAL: 60,
  POMODORO_DURATION: 15,
  
  // Decay Rates (per 60 seconds)
  DECAY_HUNGER: 5,
  DECAY_THIRST: 6,
  DECAY_CLEANLINESS: 3,
  DECAY_LOVE: 2,
  
  // Gains & Costs
  GAIN_FEED_HUNGER: 25,
  GAIN_FEED_LOVE: 5,
  
  GAIN_DRINK_THIRST: 30,
  GAIN_DRINK_LOVE: 2,
  
  GAIN_CLEAN: 35,
  
  GAIN_WORK_XP_PER_SEC: 0.5, 
  COST_WORK_HUNGER: 10,
  COST_WORK_THIRST: 10,
  COST_WORK_CLEAN: 5,
  
  GAIN_TRAIN_XP: 12,
  GAIN_TRAIN_LOVE: 4,
  COST_TRAIN_HUNGER: 6,
  COST_TRAIN_THIRST: 15,
  WEIGHT_LOSS_TRAIN: 5,
  WEIGHT_GAIN_SKIP: 5,
  
  GAIN_SLEEP_HEALTH: 10,
  GAIN_SLEEP_LOVE: 3,
  COST_SLEEP_HUNGER: 5,
  COST_SLEEP_CLEAN: 5,
  
  GAIN_SOCIAL_LOVE: 25, 
  COST_SOCIAL_HUNGER: 5,
  
  GAIN_PARTY_LOVE: 40, // High love gain
  COST_PARTY_HUNGER: 15, // High energy cost
  COST_PARTY_THIRST: 15,
  COST_PARTY_HEALTH: 5, // Dancing is tiring
  
  // Health Logic
  DAMAGE_STARVING_DIRTY: 10, 
  REGEN_HEALTH: 5,           
  
  // Thresholds
  THRESHOLD_HUNGRY: 20,
  THRESHOLD_THIRSTY: 20,
  THRESHOLD_DIRTY: 40, // Increased threshold for visible dirtiness
  THRESHOLD_LONELY: 20,
  THRESHOLD_FULL: 95,
  THRESHOLD_HAPPY_HEALTH: 50, 
};

export const VOXEL_SIZE = 1;